apiVersion: v1
kind: Service
metadata:
  labels:
    app: bootcamp
  name: bootcamp
spec:
  type: "NodePort"
  ports:
    - port: 8088
      nodePort: 31116
  selector:
    app: bootcamp
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: bootcamp
spec:
  replicas: 4
  template:
    metadata:
      labels:
        app: bootcamp
    spec:
      containers:
        - image: kradio5/kube-bootcamp:latest
          name: bootcamp
          ports:
            - containerPort: 8088
